version: "2"
services:
    code:
        build: ./docker/code
        volumes:
            - .:/code

    benchmark_doctrine_web:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes_from:
            - code
        links:
            - benchmark_doctrine_php

    benchmark_doctrine_php:
        build: ./docker/php-fpm
        volumes_from:
            - code
        links:
            - benchmark_doctrine_mysql

    benchmark_doctrine_php_cli:
        build: ./docker/php-cli
        volumes_from:
            - code
        links:
            - benchmark_doctrine_mysql

    benchmark_doctrine_mysql:
        image: mysql:5.7.17
        ports:
            - "13306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
